---
title: "Lab 6: Quarto Presentation"
format: revealjs
editor: visual
bibliography: references.bib
---

## Some Important Literature

-   This paper talks about the diversity of bacterial strains in the light organs of cardinal fish. \[\@gould_strain-level_2023\]

-   This paper covers the morphology of the fish and its luminescent light organ. \[\@leis1986\]

## A Cool Equation or Two

$$w_A(g) \equiv \prod_i^M \sum_j^M \Big( \frac{\exp(-q\epsilon d^H_{i,j})}{\sum_j \exp(-q\epsilon d^H_{i,j})} \Big) \phi^{d^A_{i,j}}$$

## References 

@article{leis1986, title = {The luminous cardinalfish Siphamia (Pisces, Apogonidae): development of larvae and the luminous organ.}, author = {Leis, Jeffrey M. and Bullock, Suzanne}, year = {1986}, date = {1986}, url = {[https://www.researchgate.net/publication/280952768},](https://www.researchgate.net/publication/280952768},) note = {Pages: 703-714}}

@article{gould_strain-level_2023, title = {Strain-level diversity of symbiont communities between individuals and populations of a bioluminescent fish}, volume = {17}, issn = {17517370}, doi = {10.1038/s41396-023-01550-6}, number = {12}, journal = {ISME Journal}, author = {Gould, A. L. and Donohoo, S. A. and Román, E. D. and Neff, E. E.}, month = dec, year = {2023}, pmid = {37891426}, note = {Publisher: Springer Nature}, pages = {2362--2369}, file = {Full Text:/Users/emilyneff/Zotero/storage/BBABD8FU/Gould et al. - 2023 - Strain-level diversity of symbiont communities bet.pdf:application/pdf},}
